# Serve Command Options
port: 9001
host: "localhost"
baseurl: "" 
detach: false
url: "https://spz.netlify.app/" 

# Build Command Options
show_drafts: false
future: false
unpublished: false
incremental: false
profile: false
strict_front_matter: true

# Global Configurations
source: "."
destination: "_site"
safe: true # Exclude directories and/or files from the conversion
exclude:
  - .asset-cache
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README

# Meta
lang: en-US
description: Stefano Pio Zingaro's Blog
# social_image_path:   /assets/img/brand/social.jpg
# social_logo_path:    /assets/img/brand/social.jpg

# Dependencies
markdown: kramdown

# Permalinks
permalink: /:categories/:slug:output_ext

# Build settings
# theme: jekyll-theme-minimal-bootstrap
plugins: # some plugins need by the theme
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: atom.xml

# Collections settings for Categories and Authors posts list pages
collections:
  pages:
    output: true
    permalink: /:name
  categories:
    output: true
    permalink: /:name/
  authors:
    output: false
    permalink: /:collection/:name/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "_categories"
      type: categories
    values:
      layout: blog
  - scope:
      path: "_authors"
      type: authors
    values:
      layout: blog
