# Handling Reading
exclude: ["README.md"]

# Outputting
compress_html:
 blanklines: true
 clippings: all
permalink: pretty

# Custom Vars
cdn:
  bs_css: "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
  bs_css_hash: "sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
  bs_js: "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
  bs_js_hash: "sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
  jquery: "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
  popper_hash: "sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
  icon_css: "https://use.fontawesome.com/releases/v5.6.3/css/all.css"
  icon_hash: "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
owner:
  name: "Stefano Pio Zingaro"
  role: "PhD student"
institution:
  name: "Università di Bologna"
  website: "https://www.unibo.it"
office:
  name: "Department of Computer Science & Engineering"
  website: "https://cs.unibo.it"
