# dependencies
kramdown:
 auto_ids: true
markdown: kramdown

# minify
compress_html:
 blanklines: true
 clippings: all

# permalinks
permalink: pretty

# vars
cdn:
  bs_css: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  bs_css_hash: "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  bs_js: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  bs_js_hash: "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  jquery: "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  popper_hash: "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  icon_css: "https://use.fontawesome.com/releases/v5.6.3/css/all.css"
  icon_hash: "sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
owner:
  name: "Stefano Pio Zingaro"
  role: "PhD student"
institution:
  name: "Università di Bologna"
  website: "https://www.unibo.it"
office:
  name: "Department of Computer Science & Engineering"
  website: "https://cs.unibo.it"
